server:
  port: 80

build.name: abc-tech-service
build.version: 0.0.2-SNAPSHOT

spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

